config/routes.rb
Rails.application.routes.draw do
  get "media_items/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "media_items#index"
  resources :media_items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/media_item.rb
class MediaItem < ApplicationRecord
    validates :category, presence: true, inclusion: { in: %w[movie series] }
    validates :release_year, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1800, less_than_or_equal_to: Date.current.year }
    validates :title, presence: true
    validates :description, presence: true
    validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }
    validates :watchlist, presence: true, inclusion: { in: %w[watched watching watchlist] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern

  before_action :load_latest_commit

  private

  def load_latest_commit
    commit_info = `git log -1 --pretty=format:"%h|%s|%cr"`
    @commit_parts = commit_info.split("|")
  end
end

app/controllers/media_items_controller.rb
class MediaItemsController < ApplicationController
  def index
    @media_items = MediaItem.order(id: :desc)
  end

  def new
    @media_item = MediaItem.new
  end

  def create
    @media_item = MediaItem.new(media_item_params)
    if @media_item.save
      redirect_to media_items_path, notice: "Media item created."
    else
      render :new
    end
  end

  def show
    @media_item = MediaItem.find(params[:id])
  end

  def edit
    @media_item = MediaItem.find(params[:id])
  end

  def update
    @media_item = MediaItem.find(params[:id])
    if @media_item.update(media_item_params)
      redirect_to media_items_path, notice: "Media item updated."
    else
      render :edit
    end
  end

  def destroy
    @media_item = MediaItem.find(params[:id])
    @media_item.destroy
    redirect_to root_path, notice: "Media item deleted."
  end

  private

  def media_item_params
    params.require(:media_item).permit(:category, :release_year, :title, :description, :rating, :watchlist)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/media_items_helper.rb
module MediaItemsHelper
    def watchlist_class(status)
      case status
      when "watched"
        "watchlist-watched"
      when "watching"
        "watchlist-watching"
      when "watchlist"
        "watchlist-watchlist"
      else
        ""
      end
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ruby Movies" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <%= favicon_link_tag 'favicon.ico' %>

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>

      <footer>
        <p>
          View on <a target="_blank" href="https://github.com/eesazahed/ruby-movies">GitHub</a>
          <% @commit_parts.each do |part| %>
            <span>| <%= part %> </span>
          <% end %>
        </p>
      </footer>
    </div>
  </body>
</html>

app/views/media_items/edit.html.erb
<h1>Edit Media Item</h1>

<%= link_to "Go back", media_items_path %>
<br />

<%= form_with model: @media_item, local: true, data: { turbo: false } do |form| %>
  <% if @media_item.errors.any? %>
    <div>
      <h2><%= pluralize(@media_item.errors.count, "error") %> prohibited this media item from saving:</h2>
      <ul>
        <% @media_item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :category %>
    <div>
      <% [['Movie', 'movie'], ['Series', 'series']].each do |label, value| %>
        <label>
          <%= form.radio_button :category, value %>
          <%= label %>
        </label>
      <% end %>
    </div>
  </div>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :release_year %>
    <%= form.number_field :release_year %>
  </div>

  <div>
    <%= form.label :rating %>
    <%= form.number_field :rating, in: 1..10 %>
  </div>

  <div>
    <%= form.label :watchlist %>
    <div>
      <% [['Watched', 'watched'], ['Watching', 'watching'], ['Watchlist', 'watchlist']].each do |label, value| %>
        <label>
          <%= form.radio_button :watchlist, value %>
          <%= label %>
        </label>
      <% end %>
    </div>
  </div>


  <div>
    <%= form.submit "Update Item" %>
  </div>
<% end %>

<form action="<%= media_item_path(@media_item) %>" method="post" onsubmit='return confirm(`Are you sure you would like to delete "<%= j @media_item.title %>"?`);'>
  <input type="hidden" name="_method" value="delete" />
  <input type="hidden" name="<%= request_forgery_protection_token %>" value="<%= form_authenticity_token %>" />
  <input type="submit" value="Delete" />
</form>

app/views/media_items/index.html.erb
<h1>Ruby Movies</h1>

<p>Have you ever wanted a simple web app to keep track of a bunch of movies/series?</p>
<p>Ruby Movies will be perfect for you!</p>

<br />
<br />

<%= link_to "Add New", new_media_item_path, class: "btn-blue" %>

<div class="table-wrapper">
  <table>
    <thead>
      <tr>
        <th>ID</th>
        <th>Category</th>
        <th>Title</th>
        <th>Description</th>
        <th>Release Year</th>
        <th>Rating</th>
        <th>Watchlist Status</th>
        <th>Created At</th>
        <th>Updated At</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @media_items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td><%= item.category.capitalize %></td>
          <td><%= item.title %></td>
          <td><%= link_to "Details", media_item_path(item) %></td>
          <td><%= item.release_year %></td>
          <td><%= item.rating %></td>
          <td class="<%= watchlist_class(item.watchlist) %>"><%= item.watchlist.capitalize %></td>
          <td><span class="created_at" data-time="<%= item.created_at.iso8601 %>"></span></td>
          <td><span class="updated_at" data-time="<%= item.updated_at.iso8601 %>"></span></td>
          <td><%= link_to "Edit", edit_media_item_path(item) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script>
  function formatLocalTimes() {
    document.querySelectorAll('.created_at, .updated_at').forEach(elem => {
      const timeString = elem.getAttribute('data-time');
      const date = new Date(timeString);

      const formatted = date.toLocaleString(undefined, {
        month: '2-digit',
        day: '2-digit',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
        hour12: false
      });

      elem.textContent = formatted;
    });
  }

  document.addEventListener('DOMContentLoaded', formatLocalTimes);
  document.addEventListener('turbo:load', formatLocalTimes);
</script>

app/views/media_items/new.html.erb
<h1>Add New Media Item</h1>

<%= link_to "Go back", media_items_path %>
<br />

<%= form_with model: @media_item, local: true, data: { turbo: false } do |form| %>
  <% if @media_item.errors.any? %>
    <div>
      <h2><%= pluralize(@media_item.errors.count, "error") %> prohibited this media item from saving:</h2>
      <ul>
        <% @media_item.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :category %>
    <div>
      <% [['Movie', 'movie'], ['Series', 'series']].each do |label, value| %>
        <label>
          <%= form.radio_button :category, value %>
          <%= label %>
        </label>
      <% end %>
    </div>
  </div>

  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :release_year %>
    <%= form.number_field :release_year %>
  </div>

  <div>
    <%= form.label :rating %>
    <%= form.number_field :rating, in: 1..10 %>
  </div>

  <div>
    <%= form.label :watchlist %>
    <div>
      <% [['Watched', 'watched'], ['Watching', 'watching'], ['Watchlist', 'watchlist']].each do |label, value| %>
        <label>
          <%= form.radio_button :watchlist, value %>
          <%= label %>
        </label>
      <% end %>
    </div>
  </div>

  <div>
    <%= form.submit "Add it to the table!" %>
  </div>
<% end %>

app/views/media_items/show.html.erb
<h1><%= @media_item.title %> (<%= @media_item.release_year %>)</h1>

<p><strong>Category:</strong> <%= @media_item.category.capitalize %></p>
<p><strong>Rating:</strong> <%= @media_item.rating %> / 10</p>
<p><strong>Status:</strong> <%= @media_item.watchlist.capitalize %></p>

<br />

<p><strong>Description:</strong></p>
<p><%= @media_item.description %></p>

<br />
<br />

<p><strong>Created at:</strong> <span class="created_at" data-time="<%= @media_item.created_at.iso8601 %>"></span></p>
<p><strong>Last updated:</strong> <span class="updated_at" data-time="<%= @media_item.updated_at.iso8601 %>"></span></p>

<br />
<br />

<%= link_to "Edit", edit_media_item_path(@media_item), class: "btn-blue" %>
<%= link_to "Back to List", media_items_path,  class: "btn-blue btn-gray"  %>

<script>
  function formatLocalTimes() {
    document.querySelectorAll('.created_at, .updated_at').forEach(elem => {
      const timeString = elem.getAttribute('data-time');
      const date = new Date(timeString);

      const formatted = date.toLocaleString(undefined, {
        month: '2-digit',
        day: '2-digit',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
        hour12: false
      });

      elem.textContent = formatted;
    });
  }

  document.addEventListener('DOMContentLoaded', formatLocalTimes);
  document.addEventListener('turbo:load', formatLocalTimes);
</script>